### PR TITLE
Added wavelet high-pass filter

### PR DESCRIPTION
**Pull request by mmyros**
Due to Martin Spacek, see function's help for usage and more information

### CODE REVIEW

**Comment by magland** [comment]
Thanks for the contribution. I guess we would need to create a wrapper so this would be a registered processor? Also, i suppose thise requires that the entire timeseries is loaded into memory?

**Comment by mmyros** [comment]
Looks like it would need a wrapper, but I am not familiar enough with the architecture of mountainsort to make one. Is there a nice write-up? It does want the entire chunk of data to be loaded in memory, but not the entire timeseries.

**Comment by magland** [comment]
The docs are in progress, but there are some pretty straightforward examples of how to do this in mountainsort/packages/pyms. I can help create it. But could you please answer the following:

I assume the input is a single (perhaps very large) timeseries dataset. Does this code do the chunking, or would that need to be done in an outer loop? Do we need to write that loop?

I assume the output will be a single filtered dataset?

What would be the parameters for this filter? (For example, the bandpass filter has freq_min, freq_max, samplerate, ...)

**Comment by mmyros** [comment]
The chunking needs to be done in an outer loop. The output is a single
chunk / dataset. The equivalent of frequency cutoff is `maxlevel` input,
and the cutoff frequency is then related to `maxlevel` and sampling
frequency (see lines 8-12 and Wiltchko 2008). In other words, it does not
require sampling frequency as input.

I'll be traveling for the next two days, but will try to look at examples
next week. Thanks!

**Comment by magland** [comment]
Okay thanks. I'll close this issue, and we can reopen then. Or better yet, send me an email and I'll invite you to the slack team.

**Pull request closed without merging**
